### ISSUE TITLE
Volume control slider disapeared.

### ISSUE THREAD

**Issue by vbsessa** [zagortenay333/ciliora-secunda-shell#1]
Hi,
The little circle that points to the current set volume level disapeared in the current version.

![captura de tela de 2016-04-07 08-56-16](https://cloud.githubusercontent.com/assets/2204164/14350423/ad235d3a-fc9f-11e5-993c-c497b9a0ac0c.png)

**Comment by zagortenay333** [comment]
I had to remove it because they messed with the `StDrawingArea` widget again...

Btw, did you edit the css? The blue color is supposed to be within the rectangle:
![screenshot from 2016-04-07 14-24-16](https://cloud.githubusercontent.com/assets/11144630/14351018/2655b48c-fccd-11e5-9a5f-7c58fd252592.png)

**Comment by vbsessa** [comment]
No, i just cutted it off from the screenshot. :-)
I just changed the default font family from Droid Sans to Lucida Sans.

**Comment by zagortenay333** [comment]
I'm talking about the slider. The blue bar is not inside the slider rectangle on your scrot.

**Comment by zagortenay333** [comment]
Btw, what version of gnome-shell are you running?

**Comment by vbsessa** [comment]
Is it not?
I'm running gnome 3.18

**Comment by zagortenay333** [comment]
This theme is made for shell `3.20`. I wrote that in the README. Older releases:
https://github.com/zagortenay333/ciliora-secunda-shell/releases

**Comment by vbsessa** [comment]
Oh, i see. I'll downgrade it then. Thanks.
